### ISSUE TITLE
Enable Clad in xeus-clang-repl

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/xeus-clang-repl#10]
Clad integrates with xeus-cling automagically. However, if we try the same approach it integrates but it fails to start as we pick up the conda build of clad that's compatible with clang5 (on which is still based xeus-cling). 

We need to find out how to tell conda to install clad built with clang15 on which is currently based xeus-clang-repl.

**Comment by vgvassilev** [comment]
Handled in conda-forge/clad-feedstock#11

**Comment by vgvassilev** [comment]
That has landed, we need to see if we can downgrade xeus-clang-repl to work with llvm14 as clad v1.0 does not yet support llvm15.

**Comment by davidlange6** [comment]
What blocks clad from supporting llvm15? (This is all developmental so going backwards seems like extra work in general...)

**Comment by vgvassilev** [comment]
We need another release of clad while for xeus-clang-repl we likely need to change a single number from `15` to `14`.
