### ISSUE TITLE
Template resolution issues with clang-repl

### ISSUE THREAD

**Issue by SylvainCorlay** [compiler-research/xeus-clang-repl#29]
clang-repl seems to have some isses with resolution of templates:

Without a non-template overload:

![Screenshot from 2023-03-30 03-57-12](https://user-images.githubusercontent.com/2397974/228708607-a1bf9eaf-5742-4f40-ad10-fa42aa7c4614.png)

With a template overload (included first)

![Screenshot from 2023-03-30 03-58-14](https://user-images.githubusercontent.com/2397974/228708610-e4c2fb6a-0caf-4203-b413-38d0bfb14e13.png)

**Comment by vgvassilev** [comment]
Thanks for the report. That seems to be a bug in clang-repl upstream. I will look at it.

**Comment by vgvassilev** [comment]
We track the issue fix here: https://reviews.llvm.org/D147319

**Comment by SylvainCorlay** [comment]
Wow, that is a quick turnaroud!

**Comment by vgvassilev** [comment]
That should be resolved, let's close it.
