### ISSUE TITLE
Building xeus-clang-repl on Apple Silicon

### ISSUE THREAD

**Issue by mcbarton** [compiler-research/xeus-clang-repl#76]
This issue will expand upon issue #75 , and detail the problems that occur when building xeus-clang-repl natively within MacOS on Apple Silicon. To aid in reproducibility I will first outline some details of my system
- Processor: M1 Pro
- Ram: 16 GB
- OS: Sonoma 14.0
- Package Manger: Macports 

One problem I came across while trying to build xeus-clang-repl was the use of the xeus/xserver_zmq.hpp header file. At least on MacOS when you install xeus this header file is not present. I had to install xeus-zmq, and change the header file to xeus-zmq/xserver_zmq.hpp .

I will make a proper start on detailing the problems with building this repo in MacOS this weekend, when I have a little more time. I will raise a separate issue in each one of the dependencies and link them back to this one.

**Comment by mcbarton** [comment]
[notes_xeus_clang_repl.txt](https://github.com/compiler-research/xeus-clang-repl/files/13403669/notes_xeus_clang_repl.txt)

I've now had a chance to rebuild xeus-clang-repl, and all its dependencies on my Apple Silicon Macbook. I've attached to this message my notes on what issues I came across while building. I still need to do a few things which are at the end of my notes, which I am hoping to have done by some time tomorrow. I also need to check how my changes may be modified by the recent commits to the https://github.com/compiler-research/CppInterOp repo. Assuming no new issues arise, then my plan is that tomorrow I will commit all my changes to the following repos, and then put in pull requests, after raising issues in the repo of each respective dependency. 

Forked repos which will contain the changes
https://github.com/mcbarton/xeus-clang-repl
https://github.com/mcbarton/CppInterOp
https://github.com/mcbarton/cppyy-backend
https://github.com/mcbarton/CPyCppyy

@vgvassilev who should I put as the reviewer of these pull requests?

**Comment by vgvassilev** [comment]
> @vgvassilev who should I put as the reviewer of these pull requests?

yes, please.

**Comment by mcbarton** [comment]
The following other issues were found which stopped xeus-clang-repl being built on Apple Silicon
- Missing #include <iostream> in include/xeus-clang-repl/xmanager.hpp caused errors with building due to use of std::cerr and others 
- xeus/xserver_zmq.hpp doesn't exist when installing xeus with MacPorts, but is available with xeus-zmq
- Linking to cxxopts::cxxopts doesn't work on my machine. Instead I pointed by machine to the location of the cxxopts folder

A pull request will be created shortly to suggest a fix for the above issues

A known unresolved issue is that xeus-clang-repl assumes that -cuda arg is being used. Apple cannot make use of Cuda gpus, and you end up getting error messages about not knowing what to do with -cuda. I attempted to fix this unsuccessfully.

After the fixes in the pull request were perfomed alongside those mentioned in linked issues I was able to build xeus-clang-repl on Apple Silicon. Not everything in the included notebooks worked with this build, but quite  a bit did.

**Comment by p4vook** [comment]
I've also worked on CMake in this project. I'll submit my changes and review your PR when I have some free time (probably in a couple of days), if you want.

**Comment by mcbarton** [comment]
> I've also worked on CMake in this project. I'll submit my changes and review your PR when I have some free time (probably in a couple of days), if you want.

@p4vook That would be great thanks. If your ok with it I may cc you in on the issue I have found with the CppInterOp cmake config file too.

**Comment by p4vook** [comment]
Yep, sure
