### ISSUE TITLE
No CI for macos

### ISSUE THREAD

**Issue by mcbarton** [compiler-research/xeus-clang-repl#81]
Currently there is only a ci for Ubuntu on x86 . I suggest the creation of a workflow which compiles on macos, now the build issues that arise from building on an arm based apple machine have been resolved. 

@vgvassilev @alexander-penev If either of you have any requirements on what you would like to see for such a workflow please put them in the comments below.

My first step towards doing this workflow would be to develop/improve the macos ci workflow for CppInterOp (issue https://github.com/compiler-research/CppInterOp/issues/138 ). I am happy to be assigned to both these issues.

**Comment by vgvassilev** [comment]
@mcbarton, that’s a great idea. Go ahead.
